#!/bin/bash

echo "ERP Database Setup Script"
echo "========================"
echo ""
echo "This script will help you run database migrations on Railway."
echo ""
echo "Steps to run migrations:"
echo "1. Open a new terminal"
echo "2. Navigate to the project: cd '/Users/saifraza/Library/Mobile Documents/com~apple~CloudDocs/Documents/Ethanol /Final documents /300/code/ERP'"
echo "3. Run: railway link (select MSPIL_ERP project)"
echo "4. Run: railway run --service cloud-api npm run migrate"
echo ""
echo "To seed demo data (optional):"
echo "5. Run: railway run --service cloud-api npm run seed"
echo ""
echo "To test the API:"
echo "curl https://cloud-api-production-0f4d.up.railway.app/health"
echo ""
echo "To test login:"
echo "curl https://cloud-api-production-0f4d.up.railway.app/api/auth/login -H 'Content-Type: application/json' -d '{\"email\": \"saif\", \"password\": \"1234\"}'"